image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

variables:
  ARTIFACT_NAME: nodejs-demo-app1.zip
  APP_NAME: nodejs-demo-app
  ENV_DEV: Preproduction

stages:
  – Build
  – Preproduction

Build:
  stage: Build
  image: alpine:latest
  script:
    – apk add –update zip
    – zip -r $ARTIFACT_NAME public views app.js package.json
  artifacts:
    paths:
      – $ARTIFACT_NAME

Preproduction:
  stage: Preproduction
    – aws s3 cp $ARTIFACT_NAME s3://$S3_BUCKET/$ARTIFACT_NAME
    – aws elasticbeanstalk create-application-version –application-name $APP_NAME –version-label v_$CI_COMMIT_SHORT_SHA –source-bundle S3Bucket=$S3_BUCKET,S3Key=$ARTIFACT_NAME
    – aws elasticbeanstalk update-environment –environment-name $ENV_DEV –version-label v_$CI_COMMIT_SHORT_SHA