version: '3'
services:
  sample-app-php-fpm:
    build: ./docker/php-fpm
    image: sample-app-php-fpm
    container_name: sample-app-php-fpm
    entrypoint: ["sh", "/usr/local/bin/init.sh", "php-fpm", "-F"]
    volumes:
      - .:/var/www/html
      - ~/.ssh:/root/.ssh

  sample-app-nginx:
    image: nginx:latest
    container_name: sample-app-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - sample-app-php-fpm
    depends_on:
      - sample-app-php-fpm
